### ISSUE TITLE
Binaries

### ISSUE THREAD

**Issue by johnandersen777** [phonkee/goexpose#5]
Hi I love goexpose!

Could you please build the binaries and upload them as a release? That would be much appreciated.

Thanks!

**Comment by phonkee** [comment]
Hi,
I am glad you like goexpose. I am working on minor improvements now and after those changes I'll bump version to 1.0 where I'll start to do tags and binaries.
Stay tuned..

**Comment by johnandersen777** [comment]
Great thanks!!!

**Comment by phonkee** [comment]
Sorry to be late, I have released version 1.0.0 with binaries for multiple operating systems
