### ISSUE TITLE
Rename the project? :)

### ISSUE THREAD

**Issue by odino** [phonkee/goexpose#6]
Yo there :)

was just coming here after reading about [nigit](https://github.com/lukasmartinelli/nigit).
I googled `goexpose` to reach the github repo and I must admit that the google results weren't great -- check yourself :)

Would suggest to rename the project to avoid confusion! ;-)

**Comment by phonkee** [comment]
Oh, that's interesting.
I have recently bought domain for goexpose so probably it's too late..
We just need to beat those nasty things in google search. :-D
