### ISSUE TITLE
go get hangs on go get gopkg.in/inf.v0

### ISSUE THREAD

**Issue by brankomijuskovic** [phonkee/goexpose#8]
Hi,

When I try to install goexpose I get:

`go get -v github.com/phonkee/goexpose`
`Fetching https://gopkg.in/inf.v0?go-get=1`
`Parsing meta tags from https://gopkg.in/inf.v0?go-get=1 (status code 200)`
`get "gopkg.in/inf.v0": found meta tag main.metaImport{Prefix:"gopkg.in/inf.v0", VCS:"git",` `RepoRoot:"https://gopkg.in/inf.v0"} at https://gopkg.in/inf.v0?go-get=1`
`gopkg.in/inf.v0 (download)`

And it hangs there forever.

`go version go1.6.2 linux/amd64`

Is there any workaround for this?

Many thanks in advance.

Best

**Comment by brankomijuskovic** [comment]
Output with clean src dir:

`go get -v github.com/phonkee/goexpose`
`github.com/phonkee/goexpose (download)`
`github.com/garyburd/redigo (download)`
`github.com/ghodss/yaml (download)`
`github.com/cloudfoundry-incubator/candiedyaml (download)`
`github.com/go-sql-driver/mysql (download)`
`github.com/gocql/gocql (download)`
`github.com/golang/snappy (download)`
`github.com/hailocab/go-hostpool (download)`
`Fetching https://golang.org/x/net/context?go-get=1`
`Parsing meta tags from https://golang.org/x/net/context?go-get=1 (status code 200)`
`get "golang.org/x/net/context": found meta tag main.metaImport{Prefix:"golang.org/x/net", VCS:"git", RepoRoot:"https://go.googlesource.com/net"} at https://golang.org/x/net/context?go-get=1`
`get "golang.org/x/net/context": verifying non-authoritative meta tag`
`Fetching https://golang.org/x/net?go-get=1`
`Parsing meta tags from https://golang.org/x/net?go-get=1 (status code 200)`
`golang.org/x/net (download)`
`Fetching https://gopkg.in/inf.v0?go-get=1`
`Parsing meta tags from https://gopkg.in/inf.v0?go-get=1 (status code 200)`
`get "gopkg.in/inf.v0": found meta tag main.metaImport{Prefix:"gopkg.in/inf.v0", VCS:"git",` `RepoRoot:"https://gopkg.in/inf.v0"} at https://gopkg.in/inf.v0?go-get=1`
`gopkg.in/inf.v0 (download)`

And hangs there forever.

Thx!

**Comment by phonkee** [comment]
Interesting I will try that later today. Thank you for report.

**Comment by technocon** [comment]
I have the same problem, any solution?

**Comment by phonkee** [comment]
I have pusblished release for 1.0.0 with compiled binaries.
